package br.com.buzzpage.rest.serviceutil;

public class TemplateConstants {

	public static final String TEMPLATE_MSG_BOAS_VINDAS = "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'><div style='margin:0 auto; width:580px;'><div style='color:#444; float:left; font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:19px; background:#F4F4F4; padding:50px; width:480px; margin:0 auto;'><div style=' border-bottom:1px solid #E6E6E6; padding:0 0 30px 0; text-align:center'><img src='http://www.buzzpage.com.br/img/logo-topo.png' /></div><br><h1 style='font-weight:normal; font-size:35px;'>$bemvindo à BuzzPage</h1><div style=' font-size:15px; line-height:24px; margin-bottom: 20px 0; '><div style=' padding:10px 10px 8px 0px; color:#444;float:left;'>Olá $nome,<br><br>Parabéns pela decisão! Seu cadastro foi realizado com sucesso!<br>A BuzzPage é o lugar onde a sua expertize é valorizada e o seu conteúdo é o rei. Ideal para você construir a sua autoridade online no assunto que você gosta e domina. <br><br/><b>Dados para acesso:</b><br/>login: $login <br/>senha: $senha<br/><br/><a href='https://drive.google.com/file/d/0B_iL8WgAK8BaeWUzd2tETUczSDg/view?usp=sharing_eid&ts=573b3e50'><li>Termo de Adesão Colaborador de Conteúdo </a><br/><li><a href='https://drive.google.com/file/d/0B2q2lLxO3XS7SlA2QWF1V3hQb0U/view'>Termo de Uso Páginas Internas</a><br/><br/></1><h3 style='color:#FF6600'>http://www.buzzpage.com.br</h3></a> </div></div><div style='border-bottom:1px solid #E6E6E6; padding-bottom:20px; margin-bottom:20px;'>Muito Obrigado<br/><strong>Em breve enviaremos muito mais novidades<br/></strong></div></div></div>";
	public static final String TEMPLATE_MENSAGEM_RECUPERAR_SENHA = "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'><div style='margin:0 auto; width:580px;'><div style='color:#444; float:left; font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:19px; background:#F4F4F4; padding:50px; width:480px; margin:0 auto;'><div style=' border-bottom:1px solid #E6E6E6; padding:0 0 30px 0; text-align:center'><img src='http://www.buzzpage.com.br/img/logo-topo.png' /></div><br><h1 style='font-weight:normal; font-size:30px;'>Nova $tipoSenha</h1><div style=' font-size:15px; line-height:24px; margin-bottom: 20px 0; '><div style=' padding:10px 10px 8px 0px; color:#444;float:left;'>Olï¿½ $nome,<br><br><b>Sua nova senha ï¿½: $senha</b><br/><br/>Para sua seguranï¿½a, aconselhamos alterar a sua $tipoSenha apï¿½s o primeiro login.<br/>Lembre-se que sua $tipoSenha ï¿½ pessoal e instransferï¿½vel.</1><h3 style='color:#FF6600'>http://www.buzzpage.com.br</h3></a> </div></div><div style='border-bottom:1px solid #E6E6E6; padding-bottom:20px; margin-bottom:20px;'>Muito Obrigado<br/><strong>Qualquer dï¿½vida, acesse nossa ï¿½rea de suporte<br/></strong></div></div></div>";

	public static final String TEMPLATE_EMAIL_MSG_DIRECAO = "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'><div style='margin:0 auto; width:580px;'><div style='color:#444; float:left; font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:19px; background:#F4F4F4; padding:50px; width:480px; margin:0 auto;'><div style=' border-bottom:1px solid #E6E6E6; padding:0 0 30px 0; text-align:center'><img src='http://www.buzzpage.com.br/img/logo-topo.png' /></div><br><h1 style='font-weight:normal; font-size:30px;'><div style=' font-size:15px; line-height:24px; margin-bottom: 20px 0; '><div style=' padding:10px 10px 8px 0px; color:#444;float:left;'>Olï¿½ $nome,<br><br/>$html</a> </div></div></div></div>";
	public static final String TEMPLATE_BLOQUEIO_DESBLOQUEIO_CONTEUDO = "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'><div style='margin:0 auto; width:580px;'><div style='color:#444; float:left; font-family:Arial, Helvetica, sans-serif; font-size:13px; line-height:19px; background:#F4F4F4; padding:50px; width:480px; margin:0 auto;'><div style=' border-bottom:1px solid #E6E6E6; padding:0 0 30px 0; text-align:center'><img src='http://www.buzzpage.com.br/img/logo-topo.png' /></div><br><h1 style='font-weight:normal; font-size:35px;'>$titulo</h1><div style=' font-size:15px; line-height:24px; margin-bottom: 20px 0; '><div style=' padding:10px 10px 8px 0px; color:#444;float:left;'>Olï¿½ $nome,<br><br>$enunciado<br><br/><b>Justificativa:</b><br/>$justificativa <br/><br/><a href='https://drive.google.com/file/d/0B_iL8WgAK8BaeWUzd2tETUczSDg/view?usp=sharing_eid&ts=573b3e50'><li>Termo de Adesï¿½o Colaborador de Conteï¿½do </a><br/><li><a href='https://drive.google.com/file/d/0B2q2lLxO3XS7SlA2QWF1V3hQb0U/view'>Termo de Uso Pï¿½ginas Internas</a><br/><br/>$obs<br/></1><h3 style='color:#FF6600'>http://www.buzzpage.com.br</h3></a> </div></div><div style='border-bottom:1px solid #E6E6E6; padding-bottom:20px; margin-bottom:20px;'>Muito Obrigado<br/><strong>Em breve enviaremos muito mais novidades<br/></strong></div></div></div>";

}
